### ISSUE TITLE
[Crash]: dark matter not marked as depenency

### ISSUE THREAD

**Issue by EthanRStokes** [constellation-mc/andromeda#71]
### What happened?

i launched the game without dark matter
instead of a dependency error showing, its a class not found exception

### Logs

```
[19:06:29] [main/ERROR]:
 A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'andromeda'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'andromeda'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.1.jar:?]
	... 2 more
Caused by: java.lang.NoClassDefFoundError: me/melontini/dark_matter/api/base/util/PrependingLogger
	at me.melontini.andromeda.util.AndromedaLog.<clinit>(AndromedaLog.java:9) ~[andromeda-1.1.0-1.20.1.jar:?]
	at me.melontini.andromeda.base.Bootstrap.<clinit>(Bootstrap.java:27) ~[andromeda-1.1.0-1.20.1.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.1.jar:?]
	... 2 more
Caused by: java.lang.ClassNotFoundException: me.melontini.dark_matter.api.base.util.PrependingLogger
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.1.jar:?]
```

### Mod Version

1.1.0

### Minecraft Version

- [ ] 1.18.2
- [ ] 1.19.x
- [ ] 1.19.3
- [X] 1.20.x

**Comment by EthanRStokes** [comment]
update: even after installing dark matter manually im still getting that error

**Comment by zenfyrdev** [comment]
Thank you for the report! 

Dark Matter is actually embedded into the jar, so you  don't need to download it. I believe this happens due to https://github.com/melontini/dark-matter/issues/4 as Fabric Loader has a weird bug where included dependencies just silently get ignored instead of crashing with a solver error. (DM is split into multiple jars, so those are double nested)

Even if you install DM separately, Fabric will still load the embedded jar of the same version, for some reason.
