### ISSUE TITLE
[Crash]: (MP) Server crashes when using the magnet

### ISSUE THREAD

**Issue by HuskyInABasket** [constellation-mc/andromeda#86]
### What happened?

Full server crash while right clicking on an item on the magnet to attune it to the magnet. I am using my custom modpack there could some conflictions with tooltip fix or travelers backpack?

### Logs

[25.12 07:34:14] [Server] [Server thread/ERROR]: Encountered an unexpected exception
[25.12 07:34:14] [Server] java.lang.NoSuchMethodError'void me.melontini.andromeda.modules.items.magnet.items.MagnetItem.itemParticles(net.minecraft.class_1799, net.minecraft.class_1657)'
[25.12 07:34:14] [Server] 	at me.melontini.andromeda.modules.items.magnet.items.MagnetItem.method_31566(MagnetItem.java:74) ~[andromeda-1.4.0-1.19.2.jar:?]
[25.12 07:34:14] [Server] 	at net.minecraft.class_1799.method_31576(class_1799.java:398) ~[server-intermediary.jar:?]
[25.12 07:34:14] [Server] 	at net.minecraft.class_1703.method_30010(class_1703.java:409) ~[server-intermediary.jar:?]
[25.12 07:34:14] [Server] 	at net.minecraft.class_1703.method_7593(class_1703.java:293) ~[server-intermediary.jar:?]
[25.12 07:34:14] [Server] 	at net.minecraft.class_3244.method_12076(class_3244.java:1770) ~[server-intermediary.jar:?]
[25.12 07:34:14] [Server] 	at net.minecraft.class_2813.method_12191(class_2813.java:58) ~[server-intermediary.jar:?]
[25.12 07:34:14] [Server] 	at net.minecraft.class_2813.method_11054(class_2813.java:13) ~[server-intermediary.jar:?]
[25.12 07:34:14] [Server] 	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
[25.12 07:34:14] [Server] 	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
[25.12 07:34:14] [Server] 	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
[25.12 07:34:14] [Server] 	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
[25.12 07:34:14] [Server] 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
[25.12 07:34:14] [Server] 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
[25.12 07:34:14] [Server] 	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
[25.12 07:34:14] [Server] 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
[25.12 07:34:14] [Server] 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
[25.12 07:34:14] [Server] 	at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
[25.12 07:34:14] [Server] 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[server-intermediary.jar:?]
[25.12 07:34:14] [Server] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
[25.12 07:34:14] [Server] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
[25.12 07:34:14] [Server] 	at java.lang.Thread.run(Thread.java:833) [?:?]
[25.12 07:34:14] [Server] [Server thread/ERROR]: This crash report has been saved to: /./crash-reports/crash-2023-12-25_07.34.14-server.txt
[25.12 07:34:14] [Server] [Analytics-Thread/WARN]: (Andromeda) [CrashHandler] Found Andromeda in trace, collecting and uploading crash report...
[25.12 07:34:14] [Server] [Server thread/INFO]: Stopping server
[25.12 07:34:14] [Server] [Server thread/INFO]: Saving players
[25.12 07:34:15] [Disconnect] HuskyInABasket has disconnected, reasonServer closed
[25.12 07:34:15] [Server] [Server thread/INFO]: HuskyInABasket left the game
[25.12 07:34:15] [Server] [Server thread/INFO]: Saving worlds
[25.12 07:34:19] [Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[25.12 07:34:19] [Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[25.12 07:34:19] [Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[25.12 07:34:19] [Server] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[25.12 07:34:19] [Server] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[25.12 07:34:19] [Server] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[25.12 07:34:19] [Server] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[25.12 07:35:39] [Server] [Server Watchdog/ERROR]: A single server tick took 80.00 seconds (should be max 0.05)
[25.12 07:35:39] [Server] [Server Watchdog/ERROR]: Considering it to be crashed, server will forcibly shutdown.
[25.12 07:35:41] [Server] Crash report:
[25.12 07:35:41] [Server] ---- Minecraft Crash Report ----
[25.12 07:35:41] [Server] // Uh... Did I do that?
[25.12 07:35:41] [Server] Time2023-12-25 07:35:41
[25.12 07:35:41] [Server] DescriptionWatching Server
[25.12 07:35:41] [Server] java.lang.ErrorWatchdog
[25.12 07:35:41] [Server] 	at net.minecraft.class_3178.run(class_3178.java:50)
[25.12 07:35:41] [Server] 	at java.base/java.lang.Thread.run(Thread.java:833)
[25.12 07:35:41] [Server] A detailed walkthrough of the error, its code path and all known details is as follows:
[25.12 07:35:41] [Server] ---------------------------------------------------------------------------------------
[25.12 07:35:41] [Server] -- Head --
[25.12 07:35:41] [Server] ThreadServer Watchdog
[25.12 07:35:41] [Server] Stacktrace:
[25.12 07:35:41] [Server] 	at net.minecraft.class_3178.run(class_3178.java:50)
[25.12 07:35:41] [Server] -- Thread Dump --
[25.12 07:35:41] [Server] Details:
[25.12 07:35:41] [Server] 	Threads"Reference Handler" daemon prio=10 Id=2 RUNNABLE
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.lang.ref.Reference.processPendingReferences(Reference.java:253)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)
[25.12 07:35:41] [Server] "Finalizer" daemon prio=Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@1e043818
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.lang.Object.wait(Native Method)
[25.12 07:35:41] [Server] 	-  waiting on java.lang.ref.ReferenceQueue$Lock@1e043818
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:172)
[25.12 07:35:41] [Server] "Signal Dispatcher" daemon prio=Id=4 RUNNABLE
[25.12 07:35:41] [Server] "Common-Cleaner" daemon prio=Id=23 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@10c3d5a8
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.lang.Object.wait(Native Method)
[25.12 07:35:41] [Server] 	-  waiting on java.lang.ref.ReferenceQueue$Lock@10c3d5a8
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)
[25.12 07:35:41] [Server] "Notification Thread" daemon prio=Id=24 RUNNABLE
[25.12 07:35:41] [Server] "HttpClient-1-SelectorManager" daemon prio=Id=65 RUNNABLE
[25.12 07:35:41] [Server] 	at java.base@17.0.8/sun.nio.ch.EPoll.wait(Native Method)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:118)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
[25.12 07:35:41] [Server] 	-  locked sun.nio.ch.Util$2@14fc5368
[25.12 07:35:41] [Server] 	-  locked sun.nio.ch.EPollSelectorImpl@51fedf93
[25.12 07:35:41] [Server] 	at java.base@17.0.8/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:141)
[25.12 07:35:41] [Server] 	at platform/java.net.http@17.0.8/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:889)
[25.12 07:35:41] [Server] "ConfigSaver" daemon prio=Id=66 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@6e85e94c
[25.12 07:35:41] [Server] 	at java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method)
[25.12 07:35:41] [Server] 	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@6e85e94c
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
[25.12 07:35:41] [Server] 	...
[25.12 07:35:41] [Server] "Timer hack thread" daemon prio=Id=73 TIMED_WAITING
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.lang.Thread.sleep(Native Method)
[25.12 07:35:41] [Server] 	at net.minecraft.class_156$9.run(class_156.java:849)
[25.12 07:35:41] [Server] "DestroyJavaVM" prio=Id=107 RUNNABLE
[25.12 07:35:41] [Server] "Thread-4" daemon prio=Id=108 TIMED_WAITING
[25.12 07:35:41] [Server] 	at java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:376)
[25.12 07:35:41] [Server] 	at com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:190)
[25.12 07:35:41] [Server] "FileSystemWatchService" daemon prio=Id=109 RUNNABLE (in native)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/sun.nio.fs.LinuxWatchService.poll(Native Method)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:314)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
[25.12 07:35:41] [Server] "Server console handler" daemon prio=Id=111 RUNNABLE (in native)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.io.FileInputStream.readBytes(Native Method)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.io.FileInputStream.read(FileInputStream.java:276)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.io.BufferedInputStream.read1(BufferedInputStream.java:282)
[25.12 07:35:41] [Server] 	at java.base@17.0.8/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
[25.12 07:35:41] [Server] 	-  locked java.io.BufferedInputStream@60e50fa1

### Mod Version

1.4.0

### Minecraft Version

- [ ] 1.18.2
- [X] 1.19.x
- [ ] 1.19.3
- [ ] 1.20.x

**Comment by zenfyrdev** [comment]
Thanks for the report! Will be fixed in 1.4.2

Btw, does right-clicking on an item with the magnet work fine?

**Comment by HuskyInABasket** [comment]
> Thanks for the report! Will be fixed in 1.4.2
> 
> Btw, does right-clicking on an item with the magnet work fine?

Right clicking causes the crash

**Comment by HuskyInABasket** [comment]
I think its those gui particles is there any way to disable those?

**Comment by zenfyrdev** [comment]
You are absolutely right about the particles. I never accounted for me forgetting to add the client check here, so there's no way to disable them.

**Comment by HuskyInABasket** [comment]
So just to confirm the gui particles are causing the crash and you will fix it in the next update?
if so I will close this

**Comment by zenfyrdev** [comment]
Yup!
